---
- name: Push SSH public key for root user
  hosts: all
  become: true
  vars:
    # You can also set this in Inventory variables or pass as extra_vars
    tower_pubkey: "{{ public_key | default('') }}"
  tasks:
    - name: Ensure root has the Tower public key
      authorized_key:
        user: root
        state: present
        key: "{{ tower_pubkey }}"
      when: tower_pubkey | length > 0

